var searchData=
[
  ['resource',['Resource',['../d9/d6f/class_com_1_1_vmware_1_1_vapi_1_1_metadata_1_1_metamodel_1_1_resource.html',1,'Com::Vmware::Vapi::Metadata::Metamodel']]],
  ['resourcebusy',['ResourceBusy',['../d3/d46/class_com_1_1_vmware_1_1_vapi_1_1_std_1_1_errors_1_1_resource_busy.html',1,'Com::Vmware::Vapi::Std::Errors']]],
  ['resourceinaccessible',['ResourceInaccessible',['../db/df3/class_com_1_1_vmware_1_1_vapi_1_1_std_1_1_errors_1_1_resource_inaccessible.html',1,'Com::Vmware::Vapi::Std::Errors']]],
  ['resourceinuse',['ResourceInUse',['../d0/d51/class_com_1_1_vmware_1_1_vapi_1_1_std_1_1_errors_1_1_resource_in_use.html',1,'Com::Vmware::Vapi::Std::Errors']]],
  ['resourcepool',['ResourcePool',['../de/d9b/class_com_1_1_vmware_1_1_vcenter_1_1_resource_pool.html',1,'Com::Vmware::Vcenter']]],
  ['resourcepooldeploymentspec',['ResourcePoolDeploymentSpec',['../d6/d63/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_library_item_1_1_resource_pool_deployment_spec.html',1,'Com::Vmware::Vcenter::Ovf::LibraryItem']]],
  ['restore',['Restore',['../d3/d1e/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_restore.html',1,'Com::Vmware::Appliance::Recovery']]],
  ['restorejobstatus',['RestoreJobStatus',['../d7/d5e/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_restore_1_1_job_1_1_restore_job_status.html',1,'Com::Vmware::Appliance::Recovery::Restore::Job']]],
  ['restorerequest',['RestoreRequest',['../d7/d4d/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_restore_1_1_restore_request.html',1,'Com::Vmware::Appliance::Recovery::Restore']]],
  ['restorerequest',['RestoreRequest',['../d9/da2/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_restore_1_1_job_1_1_restore_request.html',1,'Com::Vmware::Appliance::Recovery::Restore::Job']]],
  ['resultinfo',['ResultInfo',['../dc/d78/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_library_item_1_1_result_info.html',1,'Com::Vmware::Vcenter::Ovf::LibraryItem']]],
  ['returnresult',['ReturnResult',['../da/dea/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_backup_1_1_job_1_1_return_result.html',1,'Com::Vmware::Appliance::Recovery::Backup::Job']]],
  ['returnresult',['ReturnResult',['../d8/d8e/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_backup_1_1_return_result.html',1,'Com::Vmware::Appliance::Recovery::Backup']]],
  ['returnresult',['ReturnResult',['../df/da4/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_restore_1_1_job_1_1_return_result.html',1,'Com::Vmware::Appliance::Recovery::Restore::Job']]],
  ['returnstatus',['ReturnStatus',['../d9/dc8/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_backup_1_1_return_status.html',1,'Com::Vmware::Appliance::Recovery::Backup']]],
  ['returnstatus',['ReturnStatus',['../db/d88/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_backup_1_1_job_1_1_return_status.html',1,'Com::Vmware::Appliance::Recovery::Backup::Job']]],
  ['returnstatus',['ReturnStatus',['../d8/d34/class_com_1_1_vmware_1_1_appliance_1_1_recovery_1_1_restore_1_1_job_1_1_return_status.html',1,'Com::Vmware::Appliance::Recovery::Restore::Job']]],
  ['route',['Route',['../dd/d50/class_com_1_1_vmware_1_1_appliance_1_1_techpreview_1_1_networking_1_1_routes_1_1_route.html',1,'Com::Vmware::Appliance::Techpreview::Networking::Routes']]],
  ['routereadonly',['RouteReadOnly',['../d4/d3c/class_com_1_1_vmware_1_1_appliance_1_1_techpreview_1_1_networking_1_1_routes_1_1_route_read_only.html',1,'Com::Vmware::Appliance::Techpreview::Networking::Routes']]],
  ['routes',['Routes',['../d6/dd3/class_com_1_1_vmware_1_1_appliance_1_1_techpreview_1_1_networking_1_1_routes.html',1,'Com::Vmware::Appliance::Techpreview::Networking']]]
];
