var searchData=
[
  ['databasestorage',['Databasestorage',['../dc/d08/class_com_1_1_vmware_1_1_appliance_1_1_health_1_1_databasestorage.html',1,'Com::Vmware::Appliance::Health']]],
  ['datacenter',['Datacenter',['../d3/d69/class_com_1_1_vmware_1_1_vcenter_1_1_datacenter.html',1,'Com::Vmware::Vcenter']]],
  ['datastore',['Datastore',['../d7/de8/class_com_1_1_vmware_1_1_vcenter_1_1_inventory_1_1_datastore.html',1,'Com::Vmware::Vcenter::Inventory']]],
  ['datastore',['Datastore',['../d0/dfb/class_com_1_1_vmware_1_1_vcenter_1_1_datastore.html',1,'Com::Vmware::Vcenter']]],
  ['dcui',['Dcui',['../d0/df8/class_com_1_1_vmware_1_1_appliance_1_1_access_1_1_dcui.html',1,'Com::Vmware::Appliance::Access']]],
  ['deletefirewallrule',['DeleteFirewallRule',['../d2/d89/class_com_1_1_vmware_1_1_appliance_1_1_techpreview_1_1_networking_1_1_firewall_1_1_addr_1_1_inbound_1_1_delete_firewall_rule.html',1,'Com::Vmware::Appliance::Techpreview::Networking::Firewall::Addr::Inbound']]],
  ['deployableidentity',['DeployableIdentity',['../db/deb/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_library_item_1_1_deployable_identity.html',1,'Com::Vmware::Vcenter::Ovf::LibraryItem']]],
  ['deploymentoption',['DeploymentOption',['../dd/d73/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_deployment_option.html',1,'Com::Vmware::Vcenter::Ovf']]],
  ['deploymentoptionparams',['DeploymentOptionParams',['../dc/d49/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_deployment_option_params.html',1,'Com::Vmware::Vcenter::Ovf']]],
  ['deploymentresult',['DeploymentResult',['../d7/d7e/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_library_item_1_1_deployment_result.html',1,'Com::Vmware::Vcenter::Ovf::LibraryItem']]],
  ['deploymenttarget',['DeploymentTarget',['../d5/db2/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_library_item_1_1_deployment_target.html',1,'Com::Vmware::Vcenter::Ovf::LibraryItem']]],
  ['device',['Device',['../de/d79/class_com_1_1_vmware_1_1_vcenter_1_1_vm_1_1_hardware_1_1_boot_1_1_device.html',1,'Com::Vmware::Vcenter::Vm::Hardware::Boot']]],
  ['deviceaccesstype',['DeviceAccessType',['../d3/db4/class_com_1_1_vmware_1_1_vcenter_1_1_vm_1_1_hardware_1_1_cdrom_1_1_device_access_type.html',1,'Com::Vmware::Vcenter::Vm::Hardware::Cdrom']]],
  ['disk',['Disk',['../da/d88/class_com_1_1_vmware_1_1_vcenter_1_1_vm_1_1_hardware_1_1_disk.html',1,'Com::Vmware::Vcenter::Vm::Hardware']]],
  ['diskprovisioningtype',['DiskProvisioningType',['../d2/d30/class_com_1_1_vmware_1_1_vcenter_1_1_ovf_1_1_disk_provisioning_type.html',1,'Com::Vmware::Vcenter::Ovf']]],
  ['dnsserverconfig',['DNSServerConfig',['../db/d33/class_com_1_1_vmware_1_1_appliance_1_1_networking_1_1_dns_1_1_servers_1_1_d_n_s_server_config.html',1,'Com::Vmware::Appliance::Networking::Dns::Servers']]],
  ['dnsservermode',['DNSServerMode',['../df/de7/class_com_1_1_vmware_1_1_appliance_1_1_networking_1_1_dns_1_1_servers_1_1_d_n_s_server_mode.html',1,'Com::Vmware::Appliance::Networking::Dns::Servers']]],
  ['domains',['Domains',['../de/d07/class_com_1_1_vmware_1_1_appliance_1_1_networking_1_1_dns_1_1_domains.html',1,'Com::Vmware::Appliance::Networking::Dns']]],
  ['downloadsession',['DownloadSession',['../dc/d6e/class_com_1_1_vmware_1_1_content_1_1_library_1_1_item_1_1_download_session.html',1,'Com::Vmware::Content::Library::Item']]],
  ['downloadsessionmodel',['DownloadSessionModel',['../d3/d28/class_com_1_1_vmware_1_1_content_1_1_library_1_1_item_1_1_download_session_model.html',1,'Com::Vmware::Content::Library::Item']]],
  ['dynamicid',['DynamicID',['../d2/d44/class_com_1_1_vmware_1_1_vapi_1_1_std_1_1_dynamic_i_d.html',1,'Com::Vmware::Vapi::Std']]]
];
